name: DispenserGenerator
version: 1.0.0
main: de.mcbesser.dispensergenerator.DispenserGeneratorPlugin
api-version: "26.1.1"
author: McB_sser

commands:
  oregen:
    description: Verwaltung von Werfer Oregen
    usage: /oregen give <ofen|r\u00e4ucherofen|schmiedeofen>
    permission: dispensergenerator.admin

permissions:
  dispensergenerator.admin:
    default: op
