name: DispenserGenerator
version: 1.0.0
main: de.mcbesser.dispensergenerator.DispenserGeneratorPlugin
api-version: "1.20"
author: McB_sser

commands:
  oregen:
    description: Verwaltung von Werfer Oregen
    usage: /oregen give <ofen|räucherofen|schmiedeofen>
    permission: dispensergenerator.admin

permissions:
  dispensergenerator.admin:
    default: op
